rules:
  artipacked:
    ignore:
      - benchmark.yml
      - deploy.yml
      - fuzz.yml
      - labels.yml
      - lint.yml
      - test.yml
  unpinned-uses:
    config:
      policies:
        "*": ref-pin
