[tox]
requires =
    tox>=4.2
env_list =
    lint
    py{py3, 314, 313, 312, 311, 310}

[testenv]
deps =
    pytest
pass_env =
    FORCE_COLOR
commands =
    {envpython} -m pytest {posargs}

[testenv:lint]
skip_install = true
deps =
    prek
pass_env =
    PREK_COLOR
commands =
    prek run --all-files --show-diff-on-failure
