FROM quay.io/pypa/manylinux2014_aarch64 as build

RUN mkdir -p /io/
COPY . /io/
WORKDIR /io/

RUN bash ./scripts/build-manylinux-wheels.sh

FROM scratch as release
COPY --from=build /io/dist /wheelhouse
