name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  sync:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        with:
          prune: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
